---
- name: Create a new database
  become: true
  postgresql_db:
    name: "{{ db_name }}"
    login_host: "{{ unix_host_name }}"
    login_user: "{{ unix_user_name }}"
    login_password: "{{ unix_password }}"


- name: Connect to database and set user's password with no expire date
  become: true
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user_name }}"
    password: "{{ db_password }}"
    login_host: "{{ unix_host_name }}"
    login_user: "{{ unix_user_name }}"
    login_password: "{{ unix_password }}"
    priv: ALL
    state: present
    expires: infinity

- name: Create a new schema with name acme in test database
  become: true
  postgresql_schema:
    db: "{{ db_name }}"
    name: "{{ schema_name }}"
    login_host: "{{ unix_host_name }}"
    login_user: "{{ unix_user_name }}"
    login_password: "{{ unix_password }}"

- name: dump a database file
  copy:
    dest: /etc/migrate.sql
    src: migrate.sql
  register: sql_file_path

- name: run custom sql script
  become: true
  command: "psql -f /etc/migrate.sql"
  environment:
     PGUSER: "{{ unix_user_name }}"
     PGDATABASE: "{{ db_name }}"
     PGHOST: "{{ unix_host_name }}"
     PGPASS: "{{ unix_password }}"
  register: sql_response_file

- name: debug response
  debug:
    var: sql_response_file
